# Generated by Django 6.0.1 on 2026-01-20 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Recipes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='title',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='instructions',
            name='title',
            field=models.TextField(),
        ),
    ]
