# Generated by Django 6.0.1 on 2026-01-21 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Recipes', '0002_alter_ingredient_title_alter_instructions_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instructions',
            name='title',
            field=models.TextField(max_length=200),
        ),
    ]
