# Generated by Django 6.0.1 on 2026-01-21 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Recipes', '0003_alter_instructions_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instructions',
            name='title',
            field=models.TextField(),
        ),
    ]
