# Generated by Django 6.0.1 on 2026-01-21 00:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Recipes', '0004_alter_instructions_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='instructions',
            old_name='title',
            new_name='text',
        ),
    ]
