# Generated by Django 6.0.1 on 2026-01-21 00:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Recipes', '0005_rename_title_instructions_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingredient',
            name='title',
        ),
        migrations.AddField(
            model_name='ingredient',
            name='name',
            field=models.CharField(default=datetime.datetime(2026, 1, 21, 0, 27, 2, 184319, tzinfo=datetime.timezone.utc), max_length=100, unique=True),
            preserve_default=False,
        ),
    ]
