# Generated by Django 6.0.1 on 2026-01-22 15:37

import multiselectfield.db.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Recipes', '0012_alter_profile_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='specialty',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('italian', 'Italian'), ('pasta', 'Pasta'), ('vegetarian', 'Vegetarian'), ('vegan', 'Vegan'), ('desserts', 'Desserts'), ('baking', 'Baking'), ('quick', 'Quick Meals'), ('healthy', 'Healthy'), ('gluten_free', 'Gluten-Free'), ('seafood', 'Seafood'), ('chicken', 'Chicken'), ('beef', 'Beef'), ('breakfast', 'Breakfast'), ('brunch', 'Brunch'), ('snacks', 'Snacks'), ('soups', 'Soups & Stews'), ('salads', 'Salads'), ('bbq', 'BBQ & Grilling'), ('asian', 'Asian'), ('mexican', 'Mexican'), ('middle_eastern', 'Middle Eastern'), ('indian', 'Indian'), ('mediterranean', 'Mediterranean'), ('comfort', 'Comfort Food'), ('low_carb', 'Low-Carb'), ('high_protein', 'High-Protein'), ('kids', 'Kids Meals'), ('meal_prep', 'Meal Prep')], max_length=229),
        ),
    ]
