# Generated by Django 6.0.1 on 2026-01-22 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Recipes', '0013_alter_profile_specialty'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='specialty',
        ),
    ]
