# Generated by Django 6.0.1 on 2026-01-22 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Recipes', '0015_recipe_favorited_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipeingredient',
            name='unit',
            field=models.CharField(max_length=10),
        ),
    ]
