# Generated by Django 6.0.1 on 2026-01-22 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Recipes', '0016_alter_recipeingredient_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipeingredient',
            name='unit',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
