# Generated by Django 6.0.1 on 2026-01-22 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Recipes', '0021_alter_recipeingredient_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipeingredient',
            name='unit',
            field=models.CharField(blank=True, default='', max_length=10, null=True),
        ),
    ]
