# Generated by Django 6.0.1 on 2026-01-22 19:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Recipes', '0022_alter_recipeingredient_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='profile_picture',
            field=models.ImageField(default=datetime.datetime(2026, 1, 22, 19, 42, 13, 417158, tzinfo=datetime.timezone.utc), upload_to=''),
            preserve_default=False,
        ),
    ]
