# Generated by Django 6.0.1 on 2026-01-22 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Recipes', '0024_alter_profile_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pics/'),
        ),
    ]
